# Generated by Django 5.0.1 on 2024-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RS_id_estate', models.IntegerField()),
                ('RS_titlu', models.CharField(max_length=255)),
                ('RS_zona', models.CharField(max_length=255)),
                ('RS_total_mp', models.IntegerField()),
                ('RS_etaj', models.IntegerField()),
                ('RS_an_finalizare_constructie', models.IntegerField()),
                ('RS_stare_proprietate', models.CharField(max_length=255)),
                ('RS_pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RS_camere', models.IntegerField()),
                ('RS_bai', models.IntegerField()),
                ('RS_descriere', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_agent',
            field=models.IntegerField(),
        ),
    ]
