# Generated by Django 5.0.1 on 2024-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliare', '0002_realestate_delete_property_alter_agent_id_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='RS_compartimerntare',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
