# Generated by Django 5.0.1 on 2024-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliare', '0003_realestate_rs_compartimerntare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='RS_compartimerntare',
        ),
        migrations.AddField(
            model_name='realestate',
            name='RS_compartimentare',
            field=models.CharField(choices=[('open_space', 'Open Space'), ('semidecomandat', 'Semidecomandat'), ('decomandat', 'Decomandat'), ('circular', 'Circular'), ('nedecomandat', 'Nedecomandat')], default='open_space', max_length=255),
        ),
    ]
